[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world_example = "9zFgMcx43Aq6RdzA6vGZYKjdpoxQijD7VaYXf456W6vs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/berlin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
